In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("CooperUnion/anime-recommendations-database")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'anime-recommendations-database' dataset.
Path to dataset files: /kaggle/input/anime-recommendations-database

In [2]:
import numpy as np
import pandas as pd

In [3]:
animes = pd.read_csv(f'{path}/anime.csv')

In [4]:
animes.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [5]:
animes = animes[["anime_id", "name", "genre", "type", "episodes"]]

In [6]:
animes.head()

,anime_id,name,genre,type,episodes
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51

In [7]:
animes.shape

(12294, 5)

In [8]:
animes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
dtypes: int64(1), object(4)
memory usage: 480.4+ KB

In [9]:
animes.dropna(inplace=True)

In [10]:
animes.shape

(12210, 5)

In [11]:
animes.duplicated().sum()

np.int64(0)

In [12]:
animes['genre'].dtype

dtype('O')

In [13]:
type(animes['genre'].iloc[0])

str

In [14]:
animes['genre'] = animes['genre'].str.split(", ").apply(lambda x: [i.replace(" ", "") for i in x])

In [15]:
animes['type'] = animes['type'].str.split(" ")
animes['episodes'] = animes['episodes'].str.split(" ")

In [16]:
animes['type']

0        [Movie]
1           [TV]
2           [TV]
3           [TV]
4           [TV]
          ...
12289      [OVA]
12290      [OVA]
12291      [OVA]
12292      [OVA]
12293    [Movie]
Name: type, Length: 12210, dtype: object

In [110]:
animes['title'] = animes['name']

In [111]:
animes['tag'] = animes['genre'] + animes['type'] + animes['episodes']

In [112]:
df = animes[['anime_id', 'title' , 'tag']]

In [113]:
df.head()

,anime_id,title,tag
0,32281,Kimi no Na wa.,"[Drama, Romance, School, Supernatural, Movie, 1]"
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy, Magic, Mil..."
2,28977,Gintama°,"[Action, Comedy, Historical, Parody, Samurai, ..."
3,9253,Steins;Gate,"[Sci-Fi, Thriller, TV, 24]"
4,9969,Gintama&#039;,"[Action, Comedy, Historical, Parody, Samurai, ..."

In [114]:
df['tag'] = df['tag'].str.join(" ").str.lower()
df['tag']

/tmp/ipykernel_282/1358168271.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tag'] = df['tag'].str.join(" ").str.lower()

0                drama romance school supernatural movie 1
1        action adventure drama fantasy magic military ...
2        action comedy historical parody samurai sci-fi...
3                                    sci-fi thriller tv 24
4        action comedy historical parody samurai sci-fi...
                               ...
12289                                         hentai ova 1
12290                                         hentai ova 1
12291                                         hentai ova 4
12292                                         hentai ova 1
12293                                       hentai movie 1
Name: tag, Length: 12210, dtype: object

In [115]:
df['tag'][0]

'drama romance school supernatural movie 1'

In [116]:
# covert each word to vectors
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)

In [118]:
vectors = cv.fit_transform(df['tag']).toarray() # converting scipy matrix to array

In [133]:
cv.get_feature_names_out()

array(['10', '100', '1006', '101', '102', '103', '104', '105', '108',
       '109', '11', '110', '112', '113', '114', '115', '117', '119', '12',
       '120', '124', '125', '127', '1274', '128', '13', '130', '1306',
       '132', '136', '137', '14', '140', '141', '142', '1428', '143',
       '145', '147', '1471', '148', '15', '150', '151', '153', '154',
       '155', '156', '1565', '16', '161', '162', '163', '164', '167',
       '17', '170', '172', '175', '178', '1787', '18', '180', '1818',
       '182', '19', '191', '192', '193', '195', '199', '20', '200', '201',
       '203', '21', '22', '220', '224', '225', '23', '237', '24', '240',
       '243', '25', '26', '260', '263', '27', '276', '28', '283', '29',
       '291', '296', '30', '300', '305', '31', '312', '32', '33', '330',
       '331', '34', '35', '358', '36', '365', '366', '37', '373', '38',
       '39', '40', '41', '42', '43', '44', '45', '46', '47', '475', '48',
       '49', '50', '51', '510', '52', '526', '53', '54', '55', '56', '58',
       '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69',
       '694', '70', '71', '72', '726', '73', '74', '75', '76', '77',
       '773', '78', '79', '80', '83', '84', '85', '86', '87', '88', '90',
       '91', '92', '93', '94', '95', '96', '97', '98', '99', 'action',
       'adventure', 'cars', 'comedy', 'dementia', 'demons', 'drama',
       'ecchi', 'fantasy', 'fi', 'game', 'harem', 'hentai', 'historical',
       'horror', 'josei', 'kids', 'magic', 'martialarts', 'mecha',
       'military', 'movie', 'music', 'mystery', 'ona', 'ova', 'parody',
       'police', 'psychological', 'romance', 'samurai', 'school', 'sci',
       'seinen', 'shoujo', 'shoujoai', 'shounen', 'shounenai',
       'sliceoflife', 'space', 'special', 'sports', 'supernatural',
       'superpower', 'thriller', 'tv', 'unknown', 'vampire', 'yaoi',
       'yuri'], dtype=object)

In [119]:
from sklearn.metrics.pairwise import cosine_similarity
# 0 --> not similar
# 1 --> similar
simil = cosine_similarity(vectors)

In [67]:
simil

array([[1.        , 0.1490712 , 0.        , ..., 0.        , 0.        ,
        0.31622777],
       [0.1490712 , 1.        , 0.31622777, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.31622777, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.5       ],
       [0.31622777, 0.        , 0.        , ..., 0.5       , 0.5       ,
        1.        ]])

In [66]:
simil.shape

(12210, 12210)

In [75]:
sorted(list(enumerate(simil[0])), key = lambda x: x[1], reverse=True)[1:6]

[(1111, np.float64(0.9128709291752769)),
 (208, np.float64(0.8944271909999159)),
 (1494, np.float64(0.8944271909999159)),
 (1959, np.float64(0.8944271909999159)),
 (60, np.float64(0.7999999999999999))]

In [123]:
def recommend(anime):
  anime_idx = df[df['title'] == anime].index[0]
  dist = simil[anime_idx]
  anime_list = sorted(list(enumerate(dist)), key = lambda x: x[1], reverse=True)[1:6]
  for i in anime_list:
    print(df.iloc[i[0]].title)

df[df['name'] == 'Steins;Gate']

In [106]:
recommend('Steins;Gate')

anime_id                    383
name               Galaxy Angel
tag         comedy sci-fi tv 24
Name: 2877, dtype: object
anime_id                   3407
name                Blassreiter
tag         action sci-fi tv 24
Name: 3124, dtype: object
anime_id                                                  973
name        Glass no Kantai: La Legende du Vent de l&#039;...
tag                                    adventure sci-fi tv 24
Name: 4553, dtype: object
anime_id                   832
name        Ginsoukikou Ordian
tag         mecha sci-fi tv 24
Name: 6787, dtype: object
anime_id                         611
name                  Platonic Chain
tag         sci-fi sliceoflife tv 24
Name: 6967, dtype: object

In [126]:
recommend('Gintama°')

Gintama&#039;
Gintama&#039;: Enchousen
Gintama
Gintama (2017)
Gintama Movie: Kanketsu-hen - Yorozuya yo Eien Nare

In [131]:
import pickle
pickle.dump(df, open('animes.pkl', 'wb'))

In [132]:
pickle.dump(simil, open('simil.pkl', 'wb'))